services:
  mongodb:
    image: mongo:7.0
    container_name: make-salon-db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: make-salon-backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=salon_billing_db
      - CORS_ORIGINS=*
      - JWT_SECRET=salon-billing-secret-key-change-in-production
      - RESEND_API_KEY=
      - SENDER_EMAIL=onboarding@resend.dev
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_PHONE_NUMBER=
      - EMERGENT_LLM_KEY=
      - WA_PHONE_NUMBER_ID=1166802419838950
      - WA_BUSINESS_ACCOUNT_ID=281365598898076
      - WA_ACCESS_TOKEN=EAASA49K8D8EBRNNZAO4eZCz9fYofbtLX84VTiDvQobZCnfEBjHMirK9fOhwyHuszkRMPgs2KvxqSORYRPKQyeQTyUERcUFxOuFYwgO2Ccts3QjvD3Ab7QTp9aISwpp1eEeNM3XwCHLmyJNKMCr1rfSjJk4gMKfvfCm2vqhr1k9Sda3hQ2r4SA0dPtmzJREmNbO6TLRHmsE5hOkm0ZB4kZA2niDn7fbw0sABjyPw7hCE8ZBEb6BrGKxLFIhoeuyE7IlOQqqgW4pl78o6jEIvEIg7Okx
    depends_on:
      - mongodb
    volumes:
      - uploads_data:/app/uploads
      - ./wa_queue:/app/wa_queue

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: make-salon-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  uploads_data:
